import "./js/alert.js";
import "./js/backToTop";
import "./js/collapsibleAreas";
import "./js/forms-addressAutocomplete";
import "./js/forms-application";
import "./js/forms-payeezyGateway";
import "./js/forms-payOnlineAddressAutocomplete";
import "./js/forms-phoneNumberStyling";
import "./js/formValidation";
import "./js/geolocation";
// import "./js/geolocationPrompt";
import "./js/lazysizes.min.js";
import "./js/lazyVideo";
import "./js/nav.js";
// import "./js/payOnlineAutocomplete";
import "./js/scroll";
import "./js/time.js";
import "./js/wpcf7";
import "./js/eventButtonCallClick";
import "./js/membershipDesign";
import "./js/membershipDesignTotal.js";
