name: Test Push Trigger

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run simple command
        run: echo "Push triggered the workflow!"
